// <auto-generated>
// This code was generated by a tool.
// </auto-generated>

#nullable enable


using MegaCrit.Sts2.Core.Combat;
using MegaCrit.Sts2.Core.Commands.Builders;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Merchant;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Map;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Rewards;
using MegaCrit.Sts2.Core.Rooms;
using MegaCrit.Sts2.Core.ValueProps;
using MinionLib.Component.Core;
using MinionLib.Component.Interfaces;

namespace MinionLib.Component;

public abstract partial class CardComponent
{
    public virtual Task OnPlayPrefix(PlayerChoiceContext choiceContext, CardPlay cardPlay, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task OnPlayPostfix(PlayerChoiceContext choiceContext, CardPlay cardPlay, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task OnEnqueuePlayVfxPrefix(Creature? target, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task OnEnqueuePlayVfxPostfix(Creature? target, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task OnTurnEndInHandPrefix(PlayerChoiceContext choiceContext, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task OnTurnEndInHandPostfix(PlayerChoiceContext choiceContext, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeCardPlayedPrefix(CardPlay cardPlay, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeCardPlayedPostfix(CardPlay cardPlay, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCardPlayedPrefix(PlayerChoiceContext choiceContext, CardPlay cardPlay, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCardPlayedPostfix(PlayerChoiceContext choiceContext, CardPlay cardPlay, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCardPlayedLatePrefix(PlayerChoiceContext choiceContext, CardPlay cardPlay, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCardPlayedLatePostfix(PlayerChoiceContext choiceContext, CardPlay cardPlay, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterPlayerTurnStartEarlyPrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterPlayerTurnStartEarlyPostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterPlayerTurnStartPrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterPlayerTurnStartPostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterPlayerTurnStartLatePrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterPlayerTurnStartLatePostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterAutoPostPlayPhaseEnteredPrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterAutoPostPlayPhaseEnteredPostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterAutoPrePlayPhaseEnteredEarlyPrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterAutoPrePlayPhaseEnteredEarlyPostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterAutoPrePlayPhaseEnteredPrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterAutoPrePlayPhaseEnteredPostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterAutoPrePlayPhaseEnteredLatePrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterAutoPrePlayPhaseEnteredLatePostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeSideTurnEndVeryEarlyPrefix(PlayerChoiceContext choiceContext, CombatSide side, IEnumerable<Creature> participants, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeSideTurnEndVeryEarlyPostfix(PlayerChoiceContext choiceContext, CombatSide side, IEnumerable<Creature> participants, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeSideTurnEndEarlyPrefix(PlayerChoiceContext choiceContext, CombatSide side, IEnumerable<Creature> participants, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeSideTurnEndEarlyPostfix(PlayerChoiceContext choiceContext, CombatSide side, IEnumerable<Creature> participants, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeSideTurnEndPrefix(PlayerChoiceContext choiceContext, CombatSide side, IEnumerable<Creature> participants, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeSideTurnEndPostfix(PlayerChoiceContext choiceContext, CombatSide side, IEnumerable<Creature> participants, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterSideTurnEndPrefix(PlayerChoiceContext choiceContext, CombatSide side, IEnumerable<Creature> participants, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterSideTurnEndPostfix(PlayerChoiceContext choiceContext, CombatSide side, IEnumerable<Creature> participants, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterSideTurnEndLatePrefix(PlayerChoiceContext choiceContext, CombatSide side, IEnumerable<Creature> participants, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterSideTurnEndLatePostfix(PlayerChoiceContext choiceContext, CombatSide side, IEnumerable<Creature> participants, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterActEnteredPrefix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterActEnteredPostfix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterAddToDeckPreventedPrefix(CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterAddToDeckPreventedPostfix(CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeAttackPrefix(AttackCommand command, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeAttackPostfix(AttackCommand command, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterAttackPrefix(PlayerChoiceContext choiceContext, AttackCommand command, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterAttackPostfix(PlayerChoiceContext choiceContext, AttackCommand command, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterBlockClearedPrefix(Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterBlockClearedPostfix(Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeBlockGainedPrefix(Creature creature, decimal amount, ValueProp props, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeBlockGainedPostfix(Creature creature, decimal amount, ValueProp props, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterBlockGainedPrefix(Creature creature, decimal amount, ValueProp props, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterBlockGainedPostfix(Creature creature, decimal amount, ValueProp props, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterBlockBrokenPrefix(Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterBlockBrokenPostfix(Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCardChangedPilesPrefix(CardModel card, PileType oldPileType, AbstractModel? source, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCardChangedPilesPostfix(CardModel card, PileType oldPileType, AbstractModel? source, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCardChangedPilesLatePrefix(CardModel card, PileType oldPileType, AbstractModel? source, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCardChangedPilesLatePostfix(CardModel card, PileType oldPileType, AbstractModel? source, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCardDiscardedPrefix(PlayerChoiceContext choiceContext, CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCardDiscardedPostfix(PlayerChoiceContext choiceContext, CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCardDrawnEarlyPrefix(PlayerChoiceContext choiceContext, CardModel card, bool fromHandDraw, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCardDrawnEarlyPostfix(PlayerChoiceContext choiceContext, CardModel card, bool fromHandDraw, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCardDrawnPrefix(PlayerChoiceContext choiceContext, CardModel card, bool fromHandDraw, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCardDrawnPostfix(PlayerChoiceContext choiceContext, CardModel card, bool fromHandDraw, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCardEnteredCombatPrefix(CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCardEnteredCombatPostfix(CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCardGeneratedForCombatPrefix(CardModel card, Player? creator, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCardGeneratedForCombatPostfix(CardModel card, Player? creator, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCardExhaustedPrefix(PlayerChoiceContext choiceContext, CardModel card, bool causedByEthereal, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCardExhaustedPostfix(PlayerChoiceContext choiceContext, CardModel card, bool causedByEthereal, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeCardAutoPlayedPrefix(CardModel card, Creature? target, AutoPlayType type, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeCardAutoPlayedPostfix(CardModel card, Creature? target, AutoPlayType type, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeCombatStartPrefix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeCombatStartPostfix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeCombatStartLatePrefix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeCombatStartLatePostfix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCombatEndPrefix(CombatRoom room, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCombatEndPostfix(CombatRoom room, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCombatVictoryEarlyPrefix(CombatRoom room, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCombatVictoryEarlyPostfix(CombatRoom room, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCombatVictoryPrefix(CombatRoom room, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCombatVictoryPostfix(CombatRoom room, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCreatureAddedToCombatPrefix(Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCreatureAddedToCombatPostfix(Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCurrentHpChangedPrefix(Creature creature, decimal delta, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterCurrentHpChangedPostfix(Creature creature, decimal delta, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterDamageGivenPrefix(PlayerChoiceContext choiceContext, Creature? dealer, DamageResult result, ValueProp props, Creature target, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterDamageGivenPostfix(PlayerChoiceContext choiceContext, Creature? dealer, DamageResult result, ValueProp props, Creature target, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeDamageReceivedPrefix(PlayerChoiceContext choiceContext, Creature target, decimal amount, ValueProp props, Creature? dealer, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeDamageReceivedPostfix(PlayerChoiceContext choiceContext, Creature target, decimal amount, ValueProp props, Creature? dealer, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterDamageReceivedPrefix(PlayerChoiceContext choiceContext, Creature target, DamageResult result, ValueProp props, Creature? dealer, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterDamageReceivedPostfix(PlayerChoiceContext choiceContext, Creature target, DamageResult result, ValueProp props, Creature? dealer, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterDamageReceivedLatePrefix(PlayerChoiceContext choiceContext, Creature target, DamageResult result, ValueProp props, Creature? dealer, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterDamageReceivedLatePostfix(PlayerChoiceContext choiceContext, Creature target, DamageResult result, ValueProp props, Creature? dealer, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeDeathPrefix(Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeDeathPostfix(Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterDeathPrefix(PlayerChoiceContext choiceContext, Creature creature, bool wasRemovalPrevented, float deathAnimLength, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterDeathPostfix(PlayerChoiceContext choiceContext, Creature creature, bool wasRemovalPrevented, float deathAnimLength, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterDiedToDoomPrefix(PlayerChoiceContext choiceContext, IReadOnlyList<Creature> creatures, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterDiedToDoomPostfix(PlayerChoiceContext choiceContext, IReadOnlyList<Creature> creatures, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterEnergyResetPrefix(Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterEnergyResetPostfix(Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterEnergyResetLatePrefix(Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterEnergyResetLatePostfix(Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterEnergySpentPrefix(CardModel card, int amount, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterEnergySpentPostfix(CardModel card, int amount, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeCardRemovedPrefix(CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeCardRemovedPostfix(CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeFlushPrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeFlushPostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeFlushLatePrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeFlushLatePostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterFlushPrefix(PlayerChoiceContext choiceContext, Player player, IReadOnlyCollection<CardModel> flushedCards, IReadOnlyCollection<CardModel> retainedCards, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterFlushPostfix(PlayerChoiceContext choiceContext, Player player, IReadOnlyCollection<CardModel> flushedCards, IReadOnlyCollection<CardModel> retainedCards, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterGoldGainedPrefix(Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterGoldGainedPostfix(Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeHandDrawPrefix(Player player, PlayerChoiceContext choiceContext, ICombatState combatState, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeHandDrawPostfix(Player player, PlayerChoiceContext choiceContext, ICombatState combatState, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeHandDrawLatePrefix(Player player, PlayerChoiceContext choiceContext, ICombatState combatState, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeHandDrawLatePostfix(Player player, PlayerChoiceContext choiceContext, ICombatState combatState, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterHandEmptiedPrefix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterHandEmptiedPostfix(PlayerChoiceContext choiceContext, Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterItemPurchasedPrefix(Player player, MerchantEntry itemPurchased, int goldSpent, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterItemPurchasedPostfix(Player player, MerchantEntry itemPurchased, int goldSpent, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterMapGeneratedPrefix(ActMap map, int actIndex, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterMapGeneratedPostfix(ActMap map, int actIndex, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingBlockAmountPrefix(decimal modifiedAmount, CardModel? cardSource, CardPlay? cardPlay, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingBlockAmountPostfix(decimal modifiedAmount, CardModel? cardSource, CardPlay? cardPlay, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingCardPlayCountPrefix(CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingCardPlayCountPostfix(CardModel card, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingCardPlayResultPileOrPositionPrefix(CardModel card, PileType pileType, CardPilePosition position, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingCardPlayResultPileOrPositionPostfix(CardModel card, PileType pileType, CardPilePosition position, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingOrbPassiveTriggerCountPrefix(OrbModel orb, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingOrbPassiveTriggerCountPostfix(OrbModel orb, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingCardRewardOptionsPrefix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingCardRewardOptionsPostfix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingDamageAmountPrefix(CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingDamageAmountPostfix(CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingEnergyGainPrefix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingEnergyGainPostfix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingHandDrawPrefix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingHandDrawPostfix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterPreventingDrawPrefix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterPreventingDrawPostfix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingHpLostBeforeOstyPrefix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingHpLostBeforeOstyPostfix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingHpLostAfterOstyPrefix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingHpLostAfterOstyPostfix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingPowerAmountReceivedPrefix(PowerModel power, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingPowerAmountReceivedPostfix(PowerModel power, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingPowerAmountGivenPrefix(PowerModel power, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingPowerAmountGivenPostfix(PowerModel power, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingRewardsPrefix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterModifyingRewardsPostfix(ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterOrbChanneledPrefix(PlayerChoiceContext choiceContext, Player player, OrbModel orb, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterOrbChanneledPostfix(PlayerChoiceContext choiceContext, Player player, OrbModel orb, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterOrbEvokedPrefix(PlayerChoiceContext choiceContext, OrbModel orb, IEnumerable<Creature> targets, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterOrbEvokedPostfix(PlayerChoiceContext choiceContext, OrbModel orb, IEnumerable<Creature> targets, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterOstyRevivedPrefix(Creature osty, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterOstyRevivedPostfix(Creature osty, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforePotionUsedPrefix(PotionModel potion, Creature? target, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforePotionUsedPostfix(PotionModel potion, Creature? target, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterPotionUsedPrefix(PotionModel potion, Creature? target, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterPotionUsedPostfix(PotionModel potion, Creature? target, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterPotionDiscardedPrefix(PotionModel potion, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterPotionDiscardedPostfix(PotionModel potion, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterPotionProcuredPrefix(PotionModel potion, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterPotionProcuredPostfix(PotionModel potion, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforePowerAmountChangedPrefix(PowerModel power, decimal amount, Creature target, Creature? applier, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforePowerAmountChangedPostfix(PowerModel power, decimal amount, Creature target, Creature? applier, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterPowerAmountChangedPrefix(PlayerChoiceContext choiceContext, PowerModel power, decimal amount, Creature? applier, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterPowerAmountChangedPostfix(PlayerChoiceContext choiceContext, PowerModel power, decimal amount, Creature? applier, CardModel? cardSource, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterPreventingBlockClearPrefix(AbstractModel preventer, Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterPreventingBlockClearPostfix(AbstractModel preventer, Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterPreventingDeathPrefix(Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterPreventingDeathPostfix(Creature creature, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterRestSiteHealPrefix(Player player, bool isMimicked, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterRestSiteHealPostfix(Player player, bool isMimicked, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterRestSiteSmithPrefix(Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterRestSiteSmithPostfix(Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterRewardTakenPrefix(Player player, Reward reward, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterRewardTakenPostfix(Player player, Reward reward, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeRoomEnteredPrefix(AbstractRoom room, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeRoomEnteredPostfix(AbstractRoom room, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterRoomEnteredPrefix(AbstractRoom room, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterRoomEnteredPostfix(AbstractRoom room, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterShufflePrefix(PlayerChoiceContext choiceContext, Player shuffler, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterShufflePostfix(PlayerChoiceContext choiceContext, Player shuffler, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterStarsSpentPrefix(int amount, Player spender, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterStarsSpentPostfix(int amount, Player spender, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterStarsGainedPrefix(int amount, Player gainer, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterStarsGainedPostfix(int amount, Player gainer, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterForgePrefix(decimal amount, Player forger, AbstractModel? source, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterForgePostfix(decimal amount, Player forger, AbstractModel? source, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterSummonPrefix(PlayerChoiceContext choiceContext, Player summoner, decimal amount, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterSummonPostfix(PlayerChoiceContext choiceContext, Player summoner, decimal amount, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterTakingExtraTurnPrefix(Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterTakingExtraTurnPostfix(Player player, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterTargetingBlockedVfxPrefix(Creature blocker, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterTargetingBlockedVfxPostfix(Creature blocker, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeSideTurnStartPrefix(PlayerChoiceContext choiceContext, CombatSide side, IReadOnlyList<Creature> participants, ICombatState combatState, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task BeforeSideTurnStartPostfix(PlayerChoiceContext choiceContext, CombatSide side, IReadOnlyList<Creature> participants, ICombatState combatState, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterSideTurnStartPrefix(CombatSide side, IReadOnlyList<Creature> participants, ICombatState combatState, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterSideTurnStartPostfix(CombatSide side, IReadOnlyList<Creature> participants, ICombatState combatState, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterSideTurnStartLatePrefix(CombatSide side, IReadOnlyList<Creature> participants, ICombatState combatState, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual Task AfterSideTurnStartLatePostfix(CombatSide side, IReadOnlyList<Creature> participants, ICombatState combatState, ComponentContext componentContext)
    {
        return Task.CompletedTask;
    }
    
    public virtual void AfterTransformedFromPrefix(ComponentContext componentContext)
    {
    }
    
    public virtual void AfterTransformedFromPostfix(ComponentContext componentContext)
    {
    }
    
    public virtual void AfterTransformedToPrefix(ComponentContext componentContext)
    {
    }
    
    public virtual void AfterTransformedToPostfix(ComponentContext componentContext)
    {
    }
    
}
